//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int id { get; set; }
        public int accountId { get; set; }
        public int toolEntityId { get; set; }
        public System.DateTime date { get; set; }
        public string project { get; set; }
        public string remark { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ToolEntity ToolEntity { get; set; }
    }
}
