//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceDetail
    {
        public int MaintenanceId { get; set; }
        public int CheckDetailId { get; set; }
        public bool Success { get; set; }
        public int Id { get; set; }
    
        public virtual CheckDetail CheckDetail { get; set; }
        public virtual Maintenance Maintenance { get; set; }
    }
}
