//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasingApplication
    {
        public int id { get; set; }
        public int applicationId { get; set; }
        public System.DateTime applicationDate { get; set; }
        public byte[] picture { get; set; }
        public string billNo { get; set; }
        public int toolDefId { get; set; }
        public string remark { get; set; }
        public string state { get; set; }
        public Nullable<int> firstTrialId { get; set; }
        public Nullable<System.DateTime> firstTrialDate { get; set; }
        public Nullable<int> finalTrialId { get; set; }
        public Nullable<System.DateTime> finalTrialDate { get; set; }
        public int workCellId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual ToolDef ToolDef { get; set; }
        public virtual WorkCell WorkCell { get; set; }
    }
}
