//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapApplication
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public int ToolEntityId { get; set; }
        public int LifeCount { get; set; }
        public string Reason { get; set; }
        public System.DateTime Date { get; set; }
        public string State { get; set; }
        public Nullable<int> FirstTrialId { get; set; }
        public Nullable<System.DateTime> FirstTrialDate { get; set; }
        public Nullable<int> FinalTrialId { get; set; }
        public Nullable<System.DateTime> FinalTrialDate { get; set; }
        public int WorkCellId { get; set; }
        public Nullable<int> ScrapDocId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual ScrapDoc ScrapDoc { get; set; }
        public virtual ToolEntity ToolEntity { get; set; }
        public virtual WorkCell WorkCell { get; set; }
    }
}
