//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolEntity()
        {
            this.ConsumeReturn = new HashSet<ConsumeReturn>();
            this.Maintenance = new HashSet<Maintenance>();
            this.RepairApplication = new HashSet<RepairApplication>();
            this.ScrapApplication = new HashSet<ScrapApplication>();
        }
    
        public int Id { get; set; }
        public int ToolDefId { get; set; }
        public int UsedCount { get; set; }
        public string Location { get; set; }
        public string BillNo { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<int> BringId { get; set; }
        public string State { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumeReturn> ConsumeReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairApplication> RepairApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScrapApplication> ScrapApplication { get; set; }
        public virtual ToolDef ToolDef { get; set; }
    }
}
