//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolDef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolDef()
        {
            this.ToolEntity = new HashSet<ToolEntity>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int FamilyId { get; set; }
        public string Model { get; set; }
        public string PartNo { get; set; }
        public int UPL { get; set; }
        public int UsedForId { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public int RecordId { get; set; }
        public System.DateTime EditDate { get; set; }
        public int EditId { get; set; }
        public int WorkCellId { get; set; }
        public int PMPeriod { get; set; }
        public string State { get; set; }
        public string Picture { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual Inner Inner { get; set; }
        public virtual Inner Inner1 { get; set; }
        public virtual WorkCell WorkCell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolEntity> ToolEntity { get; set; }
    }
}
