//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolEntity()
        {
            this.ConsumeReturn = new HashSet<ConsumeReturn>();
            this.InOutStock = new HashSet<InOutStock>();
            this.Maintenance = new HashSet<Maintenance>();
            this.RepairApplication = new HashSet<RepairApplication>();
            this.ScrapApplication = new HashSet<ScrapApplication>();
        }
    
        public int id { get; set; }
        public int toolDefId { get; set; }
        public int usedCount { get; set; }
        public string location { get; set; }
        public byte[] picture { get; set; }
        public string billNo { get; set; }
        public System.DateTime regDate { get; set; }
        public System.DateTime productionDate { get; set; }
        public int bringId { get; set; }
        public string state { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumeReturn> ConsumeReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InOutStock> InOutStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairApplication> RepairApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScrapApplication> ScrapApplication { get; set; }
        public virtual ToolDef ToolDef { get; set; }
    }
}
